let window_title = "CamlCast"
let initial_width = 1024
let initial_height = 768
let fov = Float.pi /. 3.
let reference_aspect = 4. /. 3.
let move_speed = 3.6
let turn_speed = 2.1
let collision_padding = 0.15
let eye_height = 0.5
let look_sensitivity = 0.0025
let pitch_sensitivity = 0.0025
let pitch_speed = 1.2
let max_pitch = 0.75
let max_render_height = 480
let sprite_near_clip = 0.1
let max_portal_depth = 3
let max_crossings_per_step = 8
let frame_budget = 1. /. 60.
let max_frame_time = 0.1
